name: upgrade
on:
  repository_dispatch:
    types: [upgrade_tf_modules]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - env:
          VERSION: ${{ github.event.client_payload.version }}
        run: echo $VERSION
